# Generated by Django 3.0.6 on 2020-08-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
