# Generated by Django 3.0.6 on 2020-08-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_imagegallery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='urlImage_small',
            field=models.ImageField(blank=True, null=True, upload_to='images/galleries/', verbose_name='Imagen pequeña'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='urlImage',
            field=models.ImageField(upload_to='images/galleries/', verbose_name='Imagen grade'),
        ),
    ]
