# Generated by Django 3.0.6 on 2020-08-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20200806_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción'),
        ),
    ]
