# Generated by Django 3.0.6 on 2020-08-06 00:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('urlImage_wide', models.ImageField(upload_to='images/', verbose_name='Imagen Ancha')),
                ('urlImage_medium', models.ImageField(upload_to='images/', verbose_name='Imagen Mediana')),
                ('urlImage_narrow', models.ImageField(upload_to='images/', verbose_name='Imagen Angosta')),
                ('views', models.IntegerField(default=0, verbose_name='Vistas')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Noticia',
            },
        ),
    ]
