# Generated by Django 3.0.6 on 2020-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='urlImage_medium',
            field=models.ImageField(upload_to='images/news/medium', verbose_name='Imagen Mediana'),
        ),
        migrations.AlterField(
            model_name='news',
            name='urlImage_narrow',
            field=models.ImageField(upload_to='images/news/narrow', verbose_name='Imagen Angosta'),
        ),
        migrations.AlterField(
            model_name='news',
            name='urlImage_wide',
            field=models.ImageField(upload_to='images/news/wide/', verbose_name='Imagen Ancha'),
        ),
    ]
