# Generated by Django 3.0.6 on 2020-08-12 18:20

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200811_1345'),
    ]

    operations = [
    UnaccentExtension()
    ]
