# Generated by Django 3.0.6 on 2020-08-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(verbose_name='Descripción')),
                ('partner_photo', models.ImageField(upload_to='images/opinions/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Opinión',
                'verbose_name_plural': 'Opiniones',
            },
        ),
    ]
