# Generated by Django 3.0.6 on 2020-08-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='partner_photo',
            field=models.ImageField(upload_to='images/opinions/', verbose_name='Foto de Socio'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='text',
            field=models.TextField(verbose_name='Texto de la Opinión'),
        ),
    ]
